spring:
  application:
    name: greeting-service
#expondo endpoints do path actuator
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
greeting-service:
  greeting: "Cia"
  default-value: "Mundo"
